#ifndef PROFILE_H
#define PROFILE_H

#define PROFILE_CD69 0
#define PROFILE_S1PR1 1
#define PROFILE_STIM 2
#define PROFILE_STIMRATE 3
#define PROFILE_AVIDITY_LN 4
#define PROFILE_AVIDITY_PER 5
#define PROFILE_GENERATION_LN 6
#define PROFILE_FIRSTDCCONTACTTIME 7
#define PROFILE_DCBINDTIME 8

#endif // PROFILE_H
